services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: kalon
      POSTGRES_PASSWORD: kalonpass
      POSTGRES_DB: kalon
    volumes:
      - ./src/test/resources/init-pg-schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "4011:5432"

  oauth2-mock:
    image: ghcr.io/navikt/mock-oauth2-server:3.0.1
    environment:
      JSON_CONFIG_PATH: /config/mock-oauth2-server.json
    volumes:
      - ./src/test/resources/oauth2-mock-server-config.json:/config/mock-oauth2-server.json:ro
    ports:
      - "4012:8080"
