spring:
  application.name: kalon

  jpa.open-in-view: false
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}?currentSchema=${POSTGRESQL_SCHEMA}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}

springdoc.packagesToScan: org.breizhcamp.kalon.application.rest

logging.pattern.level: "[t:%X{tenant}] [u.l:%X{user.login}] [e.i:%X{event.id}] %5p"
