spring:
  datasource:
    url: jdbc:postgresql://localhost:4011/kalon
    username: kalon
    password: kalonpass

  jpa:
    show-sql: true

  security.oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:4012/kalon

server.port: 4010
