spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kalon
    username: kalon
    password: kalon
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server.port: 4007
